#!/bin/bash
export BINDLE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo -e "\033[0;35mApplying configuration from dotfiles in $BINDLE_PATH\033[0m"

# Execute the autocomplete files in each module
for autocomplete in $BINDLE_PATH/modules/*/autocomplete; do . $autocomplete; done;

# Execute the alias files in each module
for alias_script in $BINDLE_PATH/modules/*/*.alias; do . $alias_script; done;

# Load the function files in each module
for module_functions in $BINDLE_PATH/modules/*/*.functions; do . $module_functions; done;

# Execute other scripts from each module
for module_script in $BINDLE_PATH/modules/*/*.bash; do . $module_script; done;

# Add bin directorys from each module to the path
bin_dirs=($BINDLE_PATH/modules/*/bin)
PREVIOUS_IFS=$IFS IFS=':'
bin_dirs=("${bin_dirs[*]}")
IFS=$PREVIOUS_IFS
PATH=$bin_dirs:$PATH
