#!/bin/bash -x

# Autocompletes ssh hostnames using hosts already connected to and stored in ~/.ssh/known_hosts
# Borrowed from http://bit.ly/ssh-completion

complete -W "$(echo `cat ~/.ssh/known_hosts | cut -f 1 -d ' ' | sed -e s/,.*//g | uniq | grep -v "\["`;)" ssh
